### ISSUE TITLE
Collect

### ISSUE THREAD

**Issue by ivde** [arrilot/bitrix-migrations#1]
Привет.
Пробую решение, но возникает ошибка
PHP Fatal error:  Call to undefined function Arrilot\BitrixMigrations\Commands\collect() in /vendor/arrilot/bitrix-migrations/src/Commands/StatusCommand.php on line 57

Подскажи, пожалуйста, что это за функция collect в строках
https://github.com/arrilot/bitrix-migrations/blob/master/src/Commands/StatusCommand.php#L57
https://github.com/arrilot/bitrix-migrations/blob/master/src/Commands/StatusCommand.php#L80
https://github.com/arrilot/bitrix-migrations/blob/master/src/Commands/TemplatesCommand.php#L58

Конечно ее достаточно просто выкинуть, но это же не решение.

Спаисбо

**Comment by arrilot** [comment]
Пофикшено в 2.1.1
