### ISSUE TITLE
Вынести конфиг в отдельный файл

### ISSUE THREAD

**Issue by CanaryKnight** [arrilot/bitrix-migrations#14]
`vendor/arrilot/bitrix-migrations/migrator -c /path/config`

Тот же DOCUMENT_ROOT лучше вынести в конфиг, чтобы не менять/копировать исполняемый файл.

**Comment by mlavrinenko** [comment]
Постоянно вызывать с "-c" едва ли будет удобно.
Как вариант считывать из composer.json, так как это делает, например, symfony:

https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-public-directory

composer.json найти легко, считать из него информацию - тоже

**Comment by mlavrinenko** [comment]
(задача взята в работу)

**Comment by arrilot** [comment]
См комментарий в PR
