### ISSUE TITLE
Особенность работы на нескольких копиях сайта, но общей базе данных

### ISSUE THREAD

**Issue by olegpro** [arrilot/bitrix-migrations#5]
В виду некоторых особенностей проекта — сайты-песочницы разработчиков проекта используют свою копию файлов, но общие папки /bitrix/ и /upload/ на всех. Соответственно база данных одна на всех. Это может показаться странно, но, как мы считаем плюсов в нашем проекте от такой командной разработки больше :)

При такой схеме сегодня случился интересный казус. Разработчик1 написал миграцию1 в ветке1 и применил, всё хорошо. На следующий день Разработчик2 на своей копии в ветке2 написал свою миграцию2 и применил, всё тоже хорошо.

Интересный момент случился при попытке отката Разработчиком1 своей миграции1. Разработчик понял что, в его миграции1 есть неточность, ему надо её поправить, откатить и накатить снова.

При запуске команды rollback Разработчик1 получил
Migration 2017_02_17_141750_403624_migration2 was not found.
Do you want to mark it as rolled back? (y/n)

Оно и логично. Так как база данных общая, мигратор пытается откатить файл миграции2, которой у разработчика1 ещё нет (ветка1 и ветка2 пока не влиты в мастер).

Какие есть варианты решения нашей проблемки? :)

**Comment by arrilot** [comment]
> Какие есть варианты решения нашей проблемки? :)
Проще всего создать новую миграцию, скопировав в её `up()` содержимое `down()` проблемной миграции.
