### ISSUE TITLE
Class 'CModule' not found

### ISSUE THREAD

**Issue by innot667** [arrilot/bitrix-migrations#9]
Здравствуйте. 
Установил из composer в public/local/libs/arrilot/bitrix-migrations/migrator
composer в public/local
запускал и оттуда и из корня проекта (public - скопировал ту)
выставил потом файлу права -rwxrwxr-x. Ничего не помогло.
Причем если запустить файл из браузера, всё работает нормально, CModule находится, ядро подключается.

php migrator
php migrator --versioin
php migrator install
получаю такой ответ
```
<?
define("START_EXEC_PROLOG_BEFORE_1", microtime());
$GLOBALS["BX_STATE"] = "PB";
if(isset($_REQUEST["BX_STATE"])) unset($_REQUEST["BX_STATE"]);
if(isset($_GET["BX_STATE"])) unset($_GET["BX_STATE"]);
if(isset($_POST["BX_STATE"])) unset($_POST["BX_STATE"]);
if(isset($_COOKIE["BX_STATE"])) unset($_COOKIE["BX_STATE"]);
if(isset($_FILES["BX_STATE"])) unset($_FILES["BX_STATE"]);

if(!isset($USER)) {global $USER;}
if(!isset($APPLICATION)) {global $APPLICATION;}
if(!isset($DB)) {global $DB;}

require_once(dirname(__FILE__)."/../include.php");

CMain::PrologActions();
?>PHP Fatal error:  Class 'CModule' not found in projectRoot/public/migrator.php on line 21
PHP Stack trace:
PHP   1. {main}() projectRoot/public/migrator.php:0
```
что я делаю не так?

**Comment by arrilot** [comment]
Судя по всему в настройках php для cli стоит short open tags = Off а Битрикс работает только с On

**Comment by innot667** [comment]
Да, вы правы. Оказалось из консоли подключался другой файл php.ini в котором short open tags = Off.

**Comment by JackCat1** [comment]
Спасибо Вам arrilot. Несколько часов не мог понять что происходит. Скрипты через браузер работают, а через крон нет. P.S. Люди, не обновляйте git на bitrixenv НИКОГДА))))
